import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { inventoryApi } from '../api/inventory';
import { ordersApi } from '../api/orders';
import { useSimulateEvent } from '../api/simulation';
import { Badge } from '../components/Badge';
import { Toast, useToast } from '../components/Toast';
import { Button } from '../components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/Card';
import type { InventoryItem, Order, SimulateEventResponse, SimulateEventType } from '../types';

const labels: Record<SimulateEventType, string> = { NEW_URGENT_ORDER: 'New urgent order', ITEM_DAMAGED: 'Item damaged', ITEM_MISSING: 'Item missing', QC_FAILURE: 'QC failure' };
const input = 'w-full rounded-md border border-zinc-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500';
type Form = { customer: string; sku: string; quantity: string; bin: string; order: string; dueAt: string; note: string };

export function SimulateEvent() {
  const [eventType, setEventType] = useState<SimulateEventType>('NEW_URGENT_ORDER');
  const [inventory, setInventory] = useState<InventoryItem[]>([]); const [orders, setOrders] = useState<Order[]>([]);
  const [form, setForm] = useState<Form>({ customer: '', sku: '', quantity: '1', bin: '', order: '', dueAt: '', note: '' }); const [optionsLoading, setOptionsLoading] = useState(true); const [optionsError, setOptionsError] = useState<string | null>(null);
  const [result, setResult] = useState<SimulateEventResponse | null>(null); const { simulateEvent, isPending } = useSimulateEvent(); const { toasts, showToast, removeToast } = useToast();
  const stockEvent = eventType === 'ITEM_DAMAGED' || eventType === 'ITEM_MISSING';
  const loadOptions = async () => { try { setOptionsLoading(true); setOptionsError(null); const [stock, orderData] = await Promise.all([inventoryApi.getInventory(), ordersApi.getOrders()]); setInventory(stock); setOrders(orderData); } catch (error) { console.error('Simulation options failed to load', error); setOptionsError(error instanceof Error ? error.message : 'Unable to load current SKUs and orders.'); } finally { setOptionsLoading(false); } };
  useEffect(() => { void loadOptions(); }, []);
  const set = (key: keyof Form, value: string) => setForm(current => ({ ...current, [key]: value }));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { const response = await simulateEvent({ event_type: eventType, customer_name: eventType === 'NEW_URGENT_ORDER' ? form.customer.trim() : undefined, sku_id: eventType !== 'QC_FAILURE' ? Number(form.sku) : undefined, quantity: eventType !== 'QC_FAILURE' ? Number(form.quantity) : undefined, bin_id: stockEvent ? Number(form.bin) : undefined, order_id: eventType === 'QC_FAILURE' ? Number(form.order) : undefined, due_at: eventType === 'NEW_URGENT_ORDER' && form.dueAt ? new Date(form.dueAt).toISOString() : undefined, note: form.note.trim() || undefined }); setResult(response); showToast('Simulation completed successfully.', 'success'); void loadOptions(); } catch (error) { showToast(`Simulation failed: ${error instanceof Error ? error.message : 'Unknown error'}`, 'error'); } };
  const summary = result?.summary; const mode = summary?.decision_mode?.replaceAll('_', ' ');
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold text-zinc-900">Simulate Event</h1><p className="mt-1 text-sm text-zinc-600">Trigger a warehouse event and inspect the resulting decision.</p></div>{optionsLoading && <p className="text-sm text-zinc-500">Loading current SKUs and orders…</p>}{optionsError && <div className="flex items-center justify-between rounded-md border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"><span>{optionsError}</span><button onClick={() => void loadOptions()} className="font-medium underline">Retry</button></div>}
    <Card><CardHeader><CardTitle>Event details</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="space-y-4"><Field label="Event type"><select className={input} value={eventType} onChange={e => setEventType(e.target.value as SimulateEventType)}>{Object.entries(labels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field>
      {eventType === 'NEW_URGENT_ORDER' && <><Field label="Customer name"><input className={input} required value={form.customer} onChange={e => set('customer', e.target.value)} /></Field><Sku items={inventory} value={form.sku} onChange={v => set('sku', v)} /><Field label="Quantity"><input className={input} required min="1" type="number" value={form.quantity} onChange={e => set('quantity', e.target.value)} /></Field><Field label="Due at"><input className={input} required type="datetime-local" value={form.dueAt} onChange={e => set('dueAt', e.target.value)} /></Field></>}
      {stockEvent && <><Sku items={inventory} value={form.sku} onChange={v => set('sku', v)} /><Field label="Bin ID"><input className={input} required min="1" type="number" value={form.bin} onChange={e => set('bin', e.target.value)} /></Field><Field label="Quantity"><input className={input} required min="1" type="number" value={form.quantity} onChange={e => set('quantity', e.target.value)} /></Field></>}
      {eventType === 'QC_FAILURE' && <Field label="Open order"><select className={input} required value={form.order} onChange={e => set('order', e.target.value)}><option value="">Select an order…</option>{orders.filter(order => !['Dispatched', 'Cancelled'].includes(order.status)).map(order => <option key={order.id} value={order.id}>{order.order_code} — {order.customer_name}</option>)}</select></Field>}
      <Field label="Note (optional)"><textarea className={input} rows={3} value={form.note} onChange={e => set('note', e.target.value)} /></Field><div className="flex justify-end"><Button type="submit" disabled={isPending}>{isPending ? 'Simulating…' : 'Simulate Event'}</Button></div>
    </form></CardContent></Card>
    {summary && <Card className="border-blue-200 bg-blue-50"><CardHeader><div className="flex flex-wrap items-center justify-between gap-2"><CardTitle>What changed</CardTitle><div className="flex gap-2"><Badge variant="active">{labels[result.event_type]}</Badge>{mode && <Badge variant={summary.decision_mode === 'auto_executed' || summary.decision_mode === 'AUTO_EXECUTED' ? 'success' : summary.decision_mode === 'approval_required' || summary.decision_mode === 'APPROVAL_REQUIRED' ? 'warning' : 'critical'}>{mode}</Badge>}</div></div></CardHeader><CardContent className="space-y-3"><p className="rounded-md border border-blue-100 bg-white p-3 text-sm">{summary.explanation}</p>{summary.created_order_id && <p className="text-sm">Created order <strong>#{summary.created_order_id}</strong>{summary.priority_label ? ` (${summary.priority_label})` : ''}.</p>}{summary.new_order_status && <p className="text-sm">Order status: <strong>{summary.new_order_status}</strong>.</p>}{summary.inventory_changes?.map((change, index) => <p className="text-sm" key={`${change.sku_id}-${index}`}>SKU #{change.sku_id}, bin #{change.bin_id}: <strong>{change.before} → {change.after}</strong> ({change.field}).</p>)}<div className="flex flex-wrap gap-3 border-t border-blue-200 pt-3 text-sm font-medium text-blue-700">{summary.created_order_id && <Link to={`/orders/${summary.created_order_id}`}>View Order #{summary.created_order_id}</Link>}{summary.affected_order_ids?.map(id => <Link key={id} to={`/orders/${id}`}>View Order #{id}</Link>)}<Link to="/inventory">View Inventory</Link><Link to="/exceptions">View Exceptions</Link></div></CardContent></Card>}
    {toasts.map(toast => <Toast key={toast.id} message={toast.message} type={toast.type} onClose={() => removeToast(toast.id)} />)}</div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-medium text-zinc-700">{label}<span className="mt-1 block">{children}</span></label>; }
function Sku({ items, value, onChange }: { items: InventoryItem[]; value: string; onChange: (value: string) => void }) { return <Field label="SKU"><select className={input} required value={value} onChange={e => onChange(e.target.value)}><option value="">Select a SKU…</option>{items.map(item => <option key={item.sku_id} value={item.sku_id}>{item.sku_code} — {item.name}</option>)}</select></Field>; }
